name: Docker Image CI

on:
  push:
    branches: '**'
  schedule:
  - cron: 0 0 * * 6

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["5.6", "7.0", "7.1", "7.2", "7.3", "7.4", "8.0"]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile-${{ matrix.php_version }} --tag laradock/workspace:latest-${{ matrix.php_version }}
        docker image ls
    - name: Push image to Docker hub
      if: ${{ success() && (github.repository == 'laradock/workspace') && (github.ref == 'refs/heads/master') }}
      run: |
        echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
        docker push laradock/workspace:latest-${{ matrix.php_version }}
        docker logout
